---
title: IBMQAccountCredentialsInvalidToken
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsInvalidToken
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsInvalidToken
---

# qiskit.providers.ibmq.IBMQAccountCredentialsInvalidToken

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidToken" />

`IBMQAccountCredentialsInvalidToken(*message)` [GitHub](https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py "view source code")

Errors raised when an IBM Quantum Experience token is invalid.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidToken.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

