---
title: IBMQAccountCredentialsInvalidFormat
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat
---

# qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat" />

`IBMQAccountCredentialsInvalidFormat(*message)`[GitHub](https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.14/qiskit/providers/ibmq/exceptions.py "view source code")

Errors raised when the credentials format is invalid.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

