---
title: IBMQAccountCredentialsNotFound
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsNotFound
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsNotFound
---

# qiskit.providers.ibmq.IBMQAccountCredentialsNotFound

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsNotFound" />

`IBMQAccountCredentialsNotFound(*message)` [GitHub](https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.14/qiskit/providers/ibmq/exceptions.py "view source code")

Errors raised when credentials are not found.

Set the error message.

### with\_traceback

<span id="qiskit.providers.ibmq.IBMQAccountCredentialsNotFound.with_traceback" />

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.

