<span id="qiskit-pulse-pulseerror" />

# qiskit.pulse.PulseError

`PulseError(*message)`

Errors raised by the pulse module.

Set the error message.

`with_traceback()`

Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
